# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Article:
  fields:
    default: title, body
    form: title, body
  order_by: id
  relationships: tags
  filters: created_at
  search: title
  application: niksan2

LinkTag:
  fields:
    default: tag, tagged_id, tagged_type
    form: tag, tagged_id
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: niksan2

Portfolio:
  fields:
    default: name, description, image
    form: name, description, image
  order_by: 
  relationships: sites
  filters: created_at
  search: name
  application: niksan2

PortfolioSite:
  fields:
    default: portfolio, site
    form: portfolio, site
  order_by: 
  relationships:
  filters: created_at
  search: 
  application: niksan2

Post:
  fields:
    default: title, body
    form: title, short, body, date
  order_by:
  relationships: tags
  filters: created_at
  search: title
  application: niksan2

Site:
  fields:
    default: image, name, url
    form: name, url, description, date, image
  order_by: date
  relationships: portfolios
  filters: created_at
  search: name
  application: niksan2

Tag:
  fields:
    default: name, link_tags_count
    form: name
  order_by: name
  relationships: articles, link_tags, posts
  filters: created_at
  search: name
  application: niksan2

