development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: niksan_development
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: niksan2_test
  pool: 5
  username: niksan
  password: 860827
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: niksan_development
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
